server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
              defaultZone: http://peer2:8765/eureka/
  instance:
      hostname: peer1
  server:
    waitTimeInMsWhenSyncEmpty: 0
