server:
  port: 8888

management:
#SpringCloud暴露接口，暴露/bus/refresh接口
  security:
    enabled: false

#开启基本的权限，默认为true
security:
  basic:
    enabled: false
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
  client:
          serviceUrl:
              defaultZone: http://peer1:8761/eureka/,http://peer2:8765/eureka/
  #management.endpoints.web.exposure.include=bus-refresh

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/linyelai/DisConfigServer
  rabbitmq:
      host: 127.0.0.1
      port: 5672


