server:
  port: 8888

management:
  context-path: /admin
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/linyelai/DisConfigServer
  rabbitmq:
      host: 127.0.0.1
      port: 5672
---

eureka:
    client:
        serviceUrl:
            defaultZone: http://peer1:8761/eureka/,http://peer2:8765/eureka/
