eureka:
    client:
        serviceUrl:
            defaultZone: http://peer1:8761/eureka/,http://peer2:8765/eureka/
server:
    port: 8763
spring:
    application:
        name: client1
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        maxAutoRetries: 3
  hystrix:
      enabled: true
